config/routes.rb
BwNewDev::Application.routes.draw do
  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :users
	resources :works, only: [:create, :update, :destroy] do
	end

	resources :pa_links, only: [ :index, :create, :destroy, :update ] do
	end

	match '/works/progress/:id', to: 'works#progress'

  resources :projects, only: [ :index, :new, :update, :create, :edit, :destroy ] do
    get :check_number, on: :collection
  end

  match '/projects/all', to: 'projects#all'
  match '/projects/amc', to: 'projects#amc'
  match '/projects/int', to: 'projects#int'
  match '/projects/wws', to: 'projects#wws'
  match '/projects/etc', to: 'projects#etc'
  match '/projects/working/:id', to: 'projects#working'
  match '/projects/export', to: 'projects#export'
  match '/projects/release', to: 'projects#release'
  get "sessions/logout"

  controller :sessions do
    get 'login' => :new
    post 'login' => :login
  end

   root :to => 'sessions#new'

end

app/views/shared/_header.html.erb
<div class="heading clearfix">
	<h1>
		<%= image_tag("list/ttl_all.gif", :alt=> "稼働全案件",  :width=> "196", :height=> "35", :class => "btn", :id => "project_title") %>
	</h1>
	 
	<%= link_to  new_project_path, :remote => true, :id => 'create_project' do %>
			<%= image_tag("btn_newcase.gif", :width => "153", :height => "43", :alt => "新規案件作成") %>
	<% end %>

	<%= link_to  projects_path(format: "xls"), :id => "csv"  do %>
			<%= image_tag("btn_csv.gif", :width => "153", :height => "43", :alt => "CSV") %>
	<% end %>
</div>

app/views/shared/_logout.html.erb
<div id="logout">
	<ul id="logoutNavi">
		<li><a href="#">
			<%= image_tag("logout_01.gif", :alt=> "",  :width=> "148", :height=> "25", :class => "btn") %>
			</a>
			<ul>
				<li class="first">
					<%= link_to image_tag("logout_02.gif", :alt=> "",  :width=> "148", :height=> "32", :alt => "ログアウト", :class => "btn") , :controller => "sessions", :action => "logout" %>
				</li>
			</ul>
		</li>
	</ul>
</div>

app/views/shared/_tab.html.erb
<ul class="tabNavi clearfix">
	<li>
		<%= link_to "/projects/all", remote: true do %>
			<%= image_tag("list/tab_all_on.gif", :alt=> "稼働全案件",  :width=> "156", :height=> "41", :id => "all_tab") %>
		<% end %>
	</li>
	<li>
		<%= link_to "/projects/amc", remote: true do %>
			<%= image_tag("list/tab_amc_off.gif", :alt=> "AMC 運用",  :width=> "156", :height=> "41", :id => "amc_tab") %>
		<% end %>
	</li>

	<li>
		<%= link_to "/projects/int", remote: true do %>
			<%= image_tag("list/tab_int_off.gif", :alt=> "INT 運用",  :width=> "156", :height=> "41", :id => "int_tab") %>
		<% end %>
	</li>
	<li>
		<%= link_to "/projects/wws", remote: true do %>
			<%= image_tag("list/tab_wws_off.gif", :alt=> "WWS 運用",  :width=> "156", :height=> "41", :id => "wws_tab") %>
		<% end %>
	</li>
	<li>
		<%= link_to "/projects/etc", remote: true do %>
			<%= image_tag("list/tab_etc_off.gif", :alt=> "その他",  :width=> "156", :height=> "41", :id => "etc_tab") %>
		<% end %>
	</li>
	<li class="lastBtn">
		<%= link_to "/projects/release", remote: true do %>
			<%= image_tag("list/tab_released_off.gif", :alt=> "リリース済み",  :width=> "156", :height=> "41", :id => 'released_tab') %>
		<% end %>
	</li>
</ul>