config/routes.rb
BwNewDev::Application.routes.draw do
  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :users
	resources :works, only: [:create, :update, :destroy] do
	end

	resources :pa_links, only: [ :index, :create, :destroy, :update ] do
	end

	match '/works/progress/:id', to: 'works#progress'

  resources :projects, only: [ :index, :new, :update, :create, :edit, :destroy ] do
    get :check_number, on: :collection
  end

  match '/projects/all', to: 'projects#all'
  match '/projects/amc', to: 'projects#amc'
  match '/projects/int', to: 'projects#int'
  match '/projects/wws', to: 'projects#wws'
  match '/projects/etc', to: 'projects#etc'
  match '/projects/working/:id', to: 'projects#working'
  match '/projects/export', to: 'projects#export'
  match '/projects/release', to: 'projects#release'
  get "sessions/logout"

  controller :sessions do
    get 'login' => :new
    post 'login' => :login
  end

   root :to => 'sessions#new'

end

app/models/project.rb
# encoding: utf-8

class Project < ActiveRecord::Base
  attr_accessible :draft, :category, :content, :estimation, :name, :number, :release_date, :submit_date, :testup, :urls, :attached_file, :attached_file_cache, :working

  has_many :pa_links, dependent: :destroy
  belongs_to :user

  mount_uploader :attached_file, AttachedFileUploader

  validates :number, presence: true, uniqueness: true
	#validate :file_size

  def self.get_released_projects
    Project.includes(:pa_links).where("pa_links.status_id = 31")
  end

  def self.get_all_projects
    Project.all
  end

	def file_name
		read_attribute :attached_file
	end
  def self.categories
    {
      'amc' => 'AMC運用',
      'int' => 'INT運用',
      'wws' => 'WWS運用',
      'etc' => 'ETC'
    }
  end
  # CSV Download
  def self.export(projects) 
     
  end
    

  def self.categories_for_options
    categories.invert
  end 

  def self.get_estimations_for_work(id)      
      Project.connection.select("SELECT ROUND(SUM(pro.estimation) + project.estimation, 2) as estimation FROM projects project
                                    LEFT JOIN pa_links pa_link ON project.id = pa_link.project_id
                                    LEFT JOIN works pro ON pro.pa_link_id = pa_link.id
                                    WHERE project.id = #{id}")
  end

  def self.get_track_for_work(id)
      Project.connection.select( "SELECT ROUND(SUM(w.track),2) as track FROM works w
                                  LEFT JOIN pa_links pa ON w.pa_link_id = pa.id
                                  LEFT JOIN projects p ON pa.project_id = p.id
                                  WHERE p.id = #{id} AND 
                                    (  pa.status_id = 18 OR
                                    pa.status_id = 5 OR pa.status_id = 4) ")
  end 

  def self.get_track_for_image(id)
      Project.connection.select( "SELECT ROUND(SUM(w.track),2) as track FROM works w
                                  LEFT JOIN pa_links pa ON w.pa_link_id = pa.id
                                  LEFT JOIN projects p ON pa.project_id = p.id
                                  WHERE p.id = #{id} AND 
                                    ( pa.status_id = 16 OR
                                    pa.status_id = 10 OR pa.status_id = 9 )")       
  end

  def self.get_track_for_wcheck(id)
      Project.connection.select( "SELECT ROUND(SUM(w.track),2) as track FROM works w
                                  LEFT JOIN pa_links pa ON w.pa_link_id = pa.id
                                  LEFT JOIN projects p ON pa.project_id = p.id
                                  WHERE p.id = #{id} AND 
                                    ( pa.status_id = 21 OR pa.status_id = 22 )")
  end

  def self.get_track_for_release(id)
      Project.connection.select( "SELECT ROUND(SUM(w.track),2) as track FROM works w
                                  LEFT JOIN pa_links pa ON w.pa_link_id = pa.id
                                  LEFT JOIN projects p ON pa.project_id = p.id
                                  WHERE p.id = #{id} AND 
                                    ( pa.status_id = 29 OR pa.status_id = 30 OR pa.status_id = 14 OR pa.status_id = 31 )") 
  end

private
	def update_attached_file_attributes
    if attached_file.present? && attached_file_changed?
      self.file_size = asset.file.size
    end
  end
end

app/controllers/projects_controller.rb
# encoding: utf-8
class ProjectsController < ApplicationController
  before_filter :parse_params, only: [:new, :create, :test,  :confirm]
  before_filter :authenticate_user, :get_status_list
 
  # project number
  @@project_number = ''
  def index
    @projects = Project.get_all_projects   
    @released_project = Project.get_released_projects
    
    respond_to do |format|         
      format.xls
      format.html
    end
  end

  def new
  	@whole_projects = Project.all
    if params[:id]
      @project = Project.find(params[:id])
    else
      @project = Project.new(params[:project] || {})
    end
 
    @start_time = Time.now
		respond_to do | format |
			format.js
		end 
  end

  def edit 
    id = params[:id]
    @project = Project.find( params[:id] )    
    if @project.pa_links.work_charge.present?
        @work_charge_name = @project.pa_links.work_charge.work.charge_name        
      else
        @work_charge_name = "" 
      end

    if @project.pa_links.wcheck_name.present?
      @wcheck_name = @project.pa_links.wcheck_name.work.check_name
    else
      @wcheck_name = ""
    end 
               
    @@project_number = @project.number
    @start_time = Time.now

    # if the user is not dir or super user 
    unless session[:user_authority] == 1
      redirect_to projects_path
    end   
  end

  def create
    case params[:commit]
    when '確認'
    	if params[:id]
      		@project = Project.find(params[:id])
      		@project.attributes = params[:project]
    	else
      	@project = Project.new(params[:project])
    	end
			@start_time = params[:track]
			@status = 'confirm'
	    respond_to do | format |
				format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
				format.js
			end
    when '再編集'
      @project = Project.new(params[:project]) 
			@start_time = params[:track] 
      @status = 're-edit'
      respond_to do | format |
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
        format.js
      end
    when '一時保存'
    	@status = "draft"
      @project = Project.new(params[:project])
      @project.draft = 1
      @project.working = 0
      @project.user_id =current_user.id
      @project.save(validate: false)

			work = Work.new

      if params.has_key?(:progress)
				status = Status.find_by_name(params[:progress])
				@project.pa_links.create(status_id: status.id)
			else
				@project.pa_links.create(status_id: 1)
			end
			work.pa_link_id = @project.pa_links.last.id
			work.track = get_track(params[:track])
			work.save

			respond_to do | format |
				format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
				format.js
			end
    when '作成' 
    	@status = "save"
 
      if params[:id]
        @project = Project.find(params[:id])
      else
        @project = Project.new(params[:project])

        @project.user_id =current_user.id
        @project.draft = 0
        @project.working = 0
        unless @project.save
          logger.warn @project.errors.full_messages

          return render action: :new
        end
      end

      
      if params.has_key?(:progress)
				status = Status.find_by_name(params[:progress])
				@project.pa_links.create(status_id: status.id)
			else
				@project.pa_links.create(status_id: 1)
			end

			#save the track
			work = Work.new
			work.pa_link_id = @project.pa_links.last.id
			work.track = get_track(params[:track])
			work.save

      redirect_to '/projects/all'
    end
  end

  def destroy
      @project = Project.find(params[:id]) 
      @project.destroy
      redirect_to projects_path
  end 

  def update
    @project = Project.find(params[:id])     
    @project.update_attributes(params[:project])    
    pa_link = @project.pa_links.first
    if params.has_key?(:progress)
      pa_link.status_id = Status.find_by_name(params[:progress]).id
    else
      pa_link.status_id = 1        
    end
    pa_link.save
    return redirect_to projects_path
  end

  def working
      @project = Project.find(params[:id])
      @project.working = 0
      @project.save!
      render json: { working: @project.working }.to_json
  end
  # excel csv fromat (BOM + UTF8)
  def export  
    respond_to do |format|         
      format.xls { send_data "FFFFFFFF"}# { send_data @products.to_csv(col_sep: "\t") }
    end
=begin
    @projects = Project.get_released_projects 
    @filename = "All projects - #{Date.today.to_formatted_s(:db)}.csv"
    
    # Add BOM to make excel using utf8 to open csv file
    #head = 'EF BB BF'.split(' ').map{|a|a.hex.chr}.join() 

    #headers = ["案件番号", '最終進捗（何稿までか）', 'リリース日','見込み工数（合算）', '作業工数（合算）', '画像作成工数（合算）', 'Wチェック工数（合算）', 'リリース前後工数（合算）']
    #headers = ["Project Number", "Recent Progress(Draft Count)", "Release Date","Estimation(SUM)", "Work Time(SUM)", "Image Work Time(SUM)", "WCheck Time(SUM)", "Release Before Time(SUM)"] 
    headers = ["案件番号", "Recent Progress(Draft Count)", "Release Date","Estimation(SUM)", "Work Time(SUM)", "Image Work Time(SUM)", "WCheck Time(SUM)", "Release Before Time(SUM)"] 
    csv_string = CSV.generate do |csv|
      csv << headers
      @projects.each do |project|  #reading ation_id = 2, 5, 8        
        # 案件番号
        number = project.number
        # 最終進捗（何稿までか）
        #recent_progress = project.pa_links.work_count.count.to_s + "稿"
        recent_progress = project.pa_links.work_count.count.to_s + "Drafts"
        # リリース日
        release_date = project.release_date.strftime("%y-%m-%d-%I")
        
        # 見込み工数(合算)    
        e_sum = Project.get_estimations_for_work(project.id)  
        e_sum_r = 0
        unless e_sum.nil?
          e_sum_r = e_sum[0]['estimation']
        end
        # 作業工数（合算）
        w_sum = Project.get_track_for_work(project.id)
        w_sum_r = 0
        unless w_sum.nil?
          w_sum_r = w_sum[0]['track']
        end
        # 画像作成工数（合算）
        i_sum = Project.get_track_for_image(project.id)
        i_sum_r = 0
        unless i_sum.nil?
          i_sum_r = i_sum[0]['track']
        end

        # Wチェック工数（合算）
        c_sum = Project.get_track_for_wcheck(project.id)
        c_sum_r = 0
        unless c_sum.nil?
          c_sum_r = c_sum[0]['track']
        end
        # リリース前後工数（合算）
        r_sum = Project.get_track_for_release(project.id)         
        r_sum_r = 0
        unless r_sum.nil?
          r_sum_r = r_sum[0]['track']
        end

        csv << ["#{project.id}", "#{recent_progress}", "#{release_date}", "#{e_sum_r}", "#{w_sum_r}", "#{i_sum_r}", "#{c_sum_r}", "#{r_sum_r}"]

      end
    end  
      
    send_data csv_string, :type => 'text/csv;',
                          :filename => @filename
=end                      
  end

  def check_number
    number = params[:number]

    if @@project_number == number
      render text: "true"
    else
      unless Project.exists?( :number => number )
        render text: "true"
      else
        render text: "false"
      end
    end  
=begin
    unless project.blank?
      projects = Project.where('id != ?', project.id )  
    else
      render text: "true"
    end 
=end 
  end

  def all
    @type = "all"
    @projects = Project.get_all_projects
    respond_to do |format|
      format.js
    end
  end

  def amc
    @type = "amc"
    @projects = Project.where(:category => @type)
    respond_to do |format|
      format.js
    end
  end

  def int
    @type = "int"
    @projects = Project.where(:category => @type)
    respond_to do |format|
      format.js
    end
  end

  def wws
    @type = "wws"
    @projects = Project.where(:category => @type)
    respond_to do |format|
      format.js
    end
  end

  def etc
    @type = "etc"
    @projects = Project.where(:category => @type)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def release
    @projects = Project.get_released_projects

    respond_to do |format|
      format.js
      format.html
    end
  end
 BOM = "\377\376"  
private
  def convert_gb(str) 
    require 'iconv' 
    BOM + Iconv.iconv("UTF-8", str.to_s)  
  end  

  def parse_params
    return if (project = params[:project]).blank?

    %w(release_date submit_date testup).each do |field|
      next if project[field.to_sym].blank?
      if project[field.to_sym] =~ /(\d{2})-(\d{2})-(\d{2})-(\d{2})/
        year, mon, mday, hour = $1.to_i, $2.to_i, $3.to_i, $4.to_i
        year = year + 2000
        project[field.to_sym] = DateTime.new(year, mon, mday, hour)
      end
    end

    project[:estimation] = project[:estimation].to_f
  end

  def get_status_list
    lists = Status.all
    @status = Hash.new
    lists.each  do | status |
      @status[status.id] = status.name
    end

    @status
  end

  def get_track(start_time)
  	@end_time = Time.now
		track =  (@end_time - Time.parse(start_time)) / 3600
		track.round(2)
	end

end

app/helpers/projects_helper.rb
module ProjectsHelper 
	def status_name(status_list, id, work_count = 0, prev_id = 0 )  
		if ( id == 1 || id == 16 || id == 2) && work_count > 1 
			work_count.to_s + "稿依頼"
		elsif id == 17 && work_count > 1 
			work_count.to_s + "稿依頼（画像アリ）"
		elsif id == 22 && work_count > 1
			work_count.to_s + "稿テストアップ"
		elsif id == 23 && work_count > 1
			work_count.to_s + "稿確認出し中"
		elsif id == 5 && work_count > 1
			work_count.to_s + "稿依頼（Wチェック待ち）"
		elsif id == 21 && work_count > 1
			work_count.to_s + "稿依頼（修正アリ）"
		elsif id == 18
			if prev_id == 9
				if work_count == 1
				"初稿内校戻し"
				elsif work_count > 1
					work_count.to_s + "稿内校戻し"
				end
			else
				status_list[1] 
			end  
		elsif id == 29		# リリース前チェック完了
			status_list[28] # Fix、リリース前チェック  	
		elsif id == 9  
			if work_count == 1
				"初稿内校戻し"
			elsif work_count > 1
				work_count.to_s + "稿内校戻し"
			end
		elsif id == 10
			if work_count == 0
				"初稿内校戻し"
			elsif work_count > 1
				work_count.to_s + "稿内校戻し"
			end
		elsif id == 27
			status_list[5]
		elsif id == 4
			status_list[21]
		elsif id == 16
			status_list[1]  		
		else
			status_list[id]  		
		end
	end

	def action_name(status_list, id, work_count = 0)  
		if ( id == 1 || id == 16 || id == 2) && work_count > 1 
			work_count.to_s + "稿依頼"
		elsif id == 17 && work_count > 1 
			work_count.to_s + "稿依頼（画像アリ）"  
		else
			status_list[id]  		
		end
	end	

	def working_status_name(status_list, id)
		status_list[id].to_s
	end

	def time_format(tf)
		unless tf.blank?
			tf.strftime("%y-%m-%d-%I")
		else
			tf
		end
	end
 
	def action_permission(status_id)
		# status_id = current_action(id)
		if super_user
			true
		elsif ( status_id == 1 || 
				status_id == 2 || #  画像アリ
				status_id == 3 || # 中断
				status_id == 9 || # 内校戻し
				status_id == 12 || # リリース前チェック
				status_id == 16 || # 着手	
				status_id == 5 ||  # Wチェック待ち	
				status_id == 19 || # 中断 
				status_id == 21 || # 修正アリ
				status_id == 14 || # リリース待機
				status_id == 17 || # 画像
				status_id == 25 || # 画像
				status_id == 26   # 内校戻し（画像アリ）
			) && open_user
			true
		else
			false
		end
	end

  def get_file_name(path)  	 
    r_index = path.rindex("/")
    file_name = path[r_index + 1, path.length]
    file_name
  end

  def get_action_css(status_id)
  	style = current_action( status_id )
		"action status" + style.to_s
	end

	def current_action( status_id )
		if status_id == 16
			16 	#着手
		elsif status_id == 1
			16	#着手
		elsif status_id == 2
			17 	#画像
		elsif status_id == 4
			3 	#画像
		elsif status_id == 5			
			5 	#Wチェック待ち
		elsif status_id == 18 #作業ストップ
			19 	#中断
		elsif status_id == 22 #テストアップ
			22 	#テストアップ
		elsif status_id == 21 || status_id == 4 #修正アリ
			21 	#修正アリ
		elsif status_id == 23 #初稿確認出し中
			24 	#確認出し中
		elsif status_id == 25 #初稿内校戻し
			26 	#内校戻し（画像アリ）
		elsif status_id == 9 	# 内校戻し
			9	# 内校戻し
		elsif status_id == 10 	# 内校戻し中断
			3	# 初稿内校戻し
		elsif status_id == 27 	# 内校戻しWチェック待ち
			5	# 内校戻しWチェック待ち
		elsif status_id == 11 # Dir作業中
			11
		elsif status_id == 28  # Fix、リリース前チェック
			12 					# リリース前チェック完了
		elsif status_id == 29	# Dirリリース前チェック
			29					# Dirリリース前チェック	
		elsif status_id == 14	# リリース待機
			14					# リリース待機
		elsif status_id == 30	# リリース後チェック完了
			30					# リリース後チェック完了
		elsif status_id == 31	# 案件完了
			31					# 案件完了
		end 
	end
end

app/views/projects/_list.html.erb
<% if @projects.any? %>

	<% @projects.each_with_index do |project, index| %>
	<!-- action < 案件完了 -->  
		<% unless project.pa_links.exists?( :status_id => 31 ) %>
			<tr id = "project_<%= project.id %>">
				<td>
					<%= project.number %>
				</td>
				<td class="rap">
					<p class="textOverflow01">
						<span><%= project.name %></span>
					</p>
				</td>
				<td>  
					<% if project.pa_links.last.try(:status) %>

					<% 	previous_status = 0
						if project.pa_links[-2].present? %>
						<% previous_status = project.pa_links[-2].status_id %>
					<% end %>
					 
						<%= 
							status_name( @status, project.pa_links.last.status_id, project.pa_links.work_count.count, previous_status  )
						%>
					<% end %>
				</td>
				<td>
					<%= time_format(project.submit_date)%>
				</td>
				<td>
					<%= time_format(project.testup)%>
				</td>
				<td>
					<%= time_format( project.release_date ) %>
				</td>
				<td>
					<% if project.pa_links.last.work.present? %> 
			       		<% if project.pa_links.work_charge.present? %>
			        		<%= project.pa_links.work_charge.work.charge_name %>
			       		<% elsif %> 
			             	<%= project.pa_links.last.work.charge_name %>
			            <% end %> 
			     	<% end %>
				</td>
				<td>
					<% if project.pa_links.last.work.present? %> 
				   		<% if project.pa_links.wcheck_name.present? %>
				    		<%= project.pa_links.wcheck_name.work.check_name %>
				   		<% elsif %> 
				         	<%= project.pa_links.last.work.check_name %>
				        <% end %> 
				 	<% end %>
				</td>
				<td >
		      		<% if project.pa_links.last.try(:status_id) %>
				      	<% if project.draft  %>
				      		中断
				      	<% else %> 
			      			<% if project.working.to_s == "0" || project.working.to_s == ""  %>	      				
		      					<% if action_permission(project.pa_links.last.status_id) %>
		      						<%= link_to "/works/progress/#{project.id}", remote: true, :class => get_action_css(project.pa_links.last.status_id ) do %>
										<%= action_name( @status, current_action(project.pa_links.last.status_id), project.pa_links.work_count.count   ) %>
									<% end %>
		      					<% else %>
		      						<%= action_name( @status, current_action(project.pa_links.last.status_id), project.pa_links.work_count.count   ) %>
		      					<% end %> 						 
							<% else %>
									<%= working_status_name( @status, current_action(project.pa_links.last.status_id)   ) %>
							<% end %> 
						<% end %>
			      	<% else %>
			       	 <%= link_to '中断', new_project_path(id: project.id)%>
			      	<% end %>
				</td> 
				<td class="dirTd">
					<% if session[:user_authority] == 1 %>
						<%= link_to '編集', edit_project_path(id: project.id) %>
					<% else %>
						編集
					<% end %> 
				</td>
			</tr>
		<% end %>
	<% end %>
<% else %>
	<tr>
		<td colspan="10">
			案件が存在しません! 
		</td>
	</tr>
<% end %>
 

app/views/projects/_new.html.erb
<% content_for :title do %>
  新規案件作成
<% end %>

	<%= image_tag 'tit_h1_newcase.gif', alt: '新規案件作成', width: 235, height: 35 %>

<div id="mainContents">
<%= render 'form'%>
</div>

app/views/projects/_released_list.html.erb
<% if @projects.any? %>
	<% @projects.each_with_index do |project, index| %>
		<tr id = "project_<%= project.id %>">
		<td>
			<%= project.number %>
		</td>
		<td class="rap">
			<p class="textOverflow01">
				<span><%= project.name %></span>
			</p>
		</td>
		<td>
      <% if project.pa_links.last.try(:status) %>
      		<% if project.pa_links.last.status_id == 9 || project.pa_links.last.status_id == 10 %>
      			<%= status_name( @status, 25 )  %>
      		<% elsif project.pa_links.last.status_id == 27  %>
      			<%= status_name( @status, 5 )  %>
      		<% else %>
	        	<%=
	        		status_name( @status, project.pa_links.last.status_id, project.pa_links.work_count.count  )
	        	%> 
	        <% end %>
      <% end %>
		</td>
		<td>
			<%= time_format(project.submit_date)%>
		</td>
		<td>
			<%= time_format(project.testup)%>
		</td>
		<td>
			<%= time_format( project.release_date ) %>
		</td>
		<td>
			<% if project.pa_links.last.work.present? %>
				<%= project.pa_links.last.work.charge_name %>
			<% end %>
		</td>
		<td>
			 <% if project.pa_links.last.work.present? %>
				<%= project.pa_links.last.work.check_name %>
			 <% end %>
		</td>
		<td >
      		<% if project.pa_links.last.try(:status_id) %> 
      			<% if project.working.to_s == "0" || project.working.to_s == ""  %>
      				<!-- action < 案件完了 -->   
					<%= action_name( @status, current_action(project.pa_links.last.status_id), project.pa_links.work_count.count   ) %>
					 
				<% else %>
						<%= working_status_name( @status, current_action(project.pa_links.last.status_id)   ) %>
				<% end %>  
			<% end %>
		</td> 
		<td class="dirTd">
			<% if session[:user_authority] == 1 %>
				<%= link_to '編集', edit_project_path(id: project.id) %>
			<% else %>
				編集
			<% end %> 
		</td>
		</tr>
	<% end %>
<% else %>
	<tr>
		<td colspan="10">
			案件が存在しません! 
		</td>
	</tr>
<% end %>

<script> 
  $(document).ready(function(){ 
		$("#sort").tablesorter(); 
	});
</script>
 

app/views/projects/create.js.erb
<%- if @status == "confirm" %>
	$("#dialog").html("<%= escape_javascript render(:partial => 'confirm') %>");
<%- elsif @status == "re-edit" %>
	$("#dialog").html("<%= escape_javascript render(:partial => 'new') %>");
<%- elsif @status == "draft" %>
	 $("#dialog").dialog("close");
<%- end %>
var $myform = $('#project-form').idealforms(options).data('idealforms');

app/views/projects/edit.html.erb
<div id="inner">
	<h1> 
		<%= image_tag 'edit/tit_h1_edit.gif', alt: '案件編集（※要注意）', width: 284, height: 35 %>
	</h1>
	<div id = "mainContents">
		<p class="clearfix editArea">	 
			<%= link_to project_path, :confirm => "本当にこの案件を破棄しますか", :method => :delete do %>
				<button type="submit" id="editBtn">この案件を破棄</button>
			<% end %>
		</p>
		<% work_count, previous_status = 0 %>
		<% if @project.pa_links.count > 0 %>
			<!-- Project form -->
			<%= render partial:"edit/form_project" %> 
			<div id = "workbox">
				<% @project.pa_links.each_with_index do | pa_link, index | %>
					<% 
						unless pa_link == @project.pa_links.last
							@pa_link = @project.pa_links[index + 1]		
					 		
							if pa_link.status_id == 1 || pa_link.status_id == 2
								work_count += 1
							end
						%> 
							
							<!-- Action = 着手 --> 						
							<% if pa_link.status_id  == 1 %>
								<% if @pa_link.status_id == 16 %>
									<%= render partial:"edit/form_image_upload", locals: {work_count: work_count, pa_link: @pa_link }%>
								<% else %>
									<%= render partial:"edit/form_work", locals: {work_count: work_count, pa_link: @pa_link }%>   
								<% end %>
							<% elsif pa_link.status_id == 16 %>
								<%= render partial:"edit/form_work", locals: {work_count: work_count, pa_link: @pa_link }%>   
							<!-- Action = 画像等・準備中 -->
							<% elsif pa_link.status_id  == 2  %>	
								<%= render partial:"edit/form_image_upload", locals: {work_count: work_count, pa_link: @pa_link }%>
							<!-- Action = Wチェック待ち -->
							<% elsif pa_link.status_id  == 5  %>	 
								<%= render partial:"edit/form_wcheck", locals: {work_count: work_count, pa_link: @pa_link }%>
								
							<!-- Action == 修正アリ -->
							<% elsif pa_link.status_id  == 21  %> 
								<%= render partial:"edit/form_edit_work", locals: {work_count: work_count, pa_link: @pa_link }%>
							<!-- Action == テストアップ -->
							<% elsif pa_link.status_id  == 22  %>	 
								<%= render partial:"edit/form_dircheck", locals: {work_count: work_count, pa_link: @pa_link }%>
							<!-- Action == 初稿内校戻し -->
							<% elsif pa_link.status_id  == 25  %>	
								<%= render partial:"edit/form_uchiko", locals: {work_count: work_count, pa_link: @pa_link }%>
							<!-- Action == 内校戻し -->	
							<% elsif pa_link.status_id  == 9  %>
								<%= render partial:"edit/form_uchiko_work", locals: {work_count: work_count, pa_link: @pa_link }%>
							<!-- Action == 初稿確認出し中 -->		
							<% elsif pa_link.status_id  == 23  %> 
								<% if @pa_link.status_id == 28 %>
									<%= render partial:"edit/form_release_request", locals: { work_count: work_count, pa_link: @pa_link   }%> 
								<% else %>
									<%= render partial:"edit/form_dir_work_request", locals: { work_count: work_count, pa_link: @pa_link   }%> 
								<% end %>	
							<!-- Action == Fix、リリース前チェック -->			
							<% elsif pa_link.status_id  == 28  %>
								<%= render partial:"edit/form_release_before_check", locals: {work_count: work_count, pa_link: @pa_link }%>
							<!-- Action == リリース前チェック完了 -->
							<% elsif pa_link.status_id  == 29  %>			
								<%= render partial:"edit/form_dir_release_before_check", locals: {work_count: work_count, pa_link: @pa_link }%>
							<!-- Action == リリース待機 -->	
							<% elsif pa_link.status_id  == 14  %>	
								<%= render partial:"edit/form_release_check", locals: {work_count: work_count, pa_link: @pa_link }%>
							<!-- Action == リリース後チェック完了 -->	
							<% elsif pa_link.status_id  == 30  %>	
								<%= render partial:"edit/form_dir_release_check", locals: {work_count: work_count, pa_link: @pa_link }%>
							<% end %> 
						<% else %>

						<% end %>
					<% previous_status = pa_link.status_id %>
				<% end %>				
			</div>
		<% end %>
	</div>
</div>