config/routes.rb
BwNewDev::Application.routes.draw do
  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :users
	resources :works, only: [:create, :update, :destroy] do
	end

	resources :pa_links, only: [ :index, :create, :destroy, :update ] do
	end

	match '/works/progress/:id', to: 'works#progress'

  resources :projects, only: [ :index, :new, :update, :create, :edit, :destroy ] do
    get :check_number, on: :collection
  end

  match '/projects/all', to: 'projects#all'
  match '/projects/amc', to: 'projects#amc'
  match '/projects/int', to: 'projects#int'
  match '/projects/wws', to: 'projects#wws'
  match '/projects/etc', to: 'projects#etc'
  match '/projects/working/:id', to: 'projects#working'
  match '/projects/export', to: 'projects#export'
  match '/projects/release', to: 'projects#release'
  get "sessions/logout"

  controller :sessions do
    get 'login' => :new
    post 'login' => :login
  end

   root :to => 'sessions#new'

end

app/views/edit/_form_dir_release_before_check.html.erb
<h2 class="popup">	
	<%= image_tag 'popup/tit_h2_dir_release_before_check.gif', alt: 'リリース前チェック', width: 178, height: 18 %>
</h2>

<%= form_for( pa_link, html: { class: 'edit-form', multipart: true }) do |f| %>
	 <%= hidden_field_tag :project_id, @project.id %> 
	 <%= hidden_field_tag :track, @start_time %>
	 	 
	<table>
		<tr>
			<td>
				<div class="t_ht"><div class="txt"><%= f.label :charge_name, '担当名:' %></div></div>
			</td>

			<td>
				<div class="d_ht">
					<div class="frm">							  
						<% if pa_link.work.present? %>
							<%= f.text_field :charge_name, value: pa_link.work.charge_name %>
						<% else %>
							<%= f.text_field :charge_name  %>	
						<% end %> 	
					</div>
				</div>
			</td>
		</tr>

		<tr>
				<td>
					<div class="t_ht"><div class="txt"><%= f.label :contact, '連絡事項:' %></div></div>
				</td>

				<td>
					<div class="d_ht">
						<div class="frm">								 
							<% if pa_link.work.present? %>
							<%= f.text_area :charge_name, value: pa_link.work.contact %>
						<% else %>
							<%= f.text_area :contact  %>	
						<% end %> 							
						</div>
					</div>
				</td>
		</tr> 
		<tr>
			<td><div class="t_ht"><div class="txt"><label>添付：</label></div></div></td>
			<td>
				<div class="d_ht">
					<div class="frm">
						<%= f.file_field :attached_file %>
						<% unless pa_link.work.file_name.blank? %> 
							<div class="file1">
								・ <a href="<%= pa_link.work.attached_file %>">
									<%= pa_link.work.file_name %>
								  </a>
							</div>
						<% end %>	
					</div>
				</div>
			</td>
		</tr>
	</table>
<!-- Radio -->
<div class="innerStepRadio clearfix">
	<div id="sts">
	    <%= f.label '進捗：' %>
	    <label>
	      <%= radio_button_tag :process, 'リリース待機' %>
	      <p class="nam">リリース待機</p>
	    </label>
	 
	    <span id="p_error">Please check!</span> 
	</div>
</div>
<%= render partial:"edit/update_btn", locals: {f: f, pa_link: pa_link} %>
<% end %>

app/views/edit/_form_dir_release_check.html.erb
<h2 class="popup">	
	<%= image_tag 'popup/tit_h1_release_check.gif', alt: 'Dirリリース待機', width: 151, height: 18 %>
</h2>

<%= form_for( pa_link, html: { class: 'edit-form', multipart: true }) do |f| %>
	<%= hidden_field_tag :project_id, @project.id %> 
	<%= hidden_field_tag :track, @start_time %>	 	 
	 
	<table>
		<tr>
			<td>
				<div class="t_ht"><div class="txt"><%= f.label :charge_name, '担当名:' %></div></div>
			</td>

			<td>
				<div class="d_ht">
					<div class="frm">	
						<% if pa_link.work.present? %>
							<%= f.text_field :charge_name, value: pa_link.work.charge_name %>
						<% else %>
							<%= f.text_field :charge_name  %>	
						<% end %> 	 
					</div>
				</div>
			</td>
		</tr> 
	</table>
<!-- Radio -->
<div class="innerStepRadio clearfix">
	<div id="sts">
	    <%= f.label '進捗：' %>
	    <label>
	      <%= radio_button_tag :process, '案件完了' %>
	      <p class="nam">案件完了</p>
	    </label>
	 
	    <span id="p_error">Please check!</span> 
	</div>
</div>

<%= render partial:"edit/update_btn", locals: {f: f, pa_link: pa_link} %>
<% end %>

app/views/edit/_form_dir_work_request.erb
<h2 class="popup"> 
	<%= dir_h2_title(work_count) %>
</h2>
 
<%= form_for( pa_link, html: { class: 'edit-form', multipart: true }) do |f| %>
	 <%= hidden_field_tag :project_id, @project.id %> 
	 <%= hidden_field_tag :track, @start_time %>
	  
	<table>
		<tr>
			<td>
				<div class="t_ht"><div class="txt"><%= f.label :charge_name, '担当名:' %></div></div>
			</td>

			<td>
				<div class="d2_ht">
					<div class="txt">
						<% if pa_link.work.present? %>
							<%= pa_link.work.charge_name %>
						<% else %>
							<%= f.text_field :charge_name %>
						<% end %>
					</div>
				</div>
			</td>

			<td>	
				<div class="t_ht"><div class="txt"><%= f.label :release_date, 'リリース日：' %></div></div>
			</td>

			<td>
				<div class="d2_ht">
					<div class="txt">
						<% if pa_link.work.present? %>
							<%= f.text_field :release_date, value: pa_link.work.release_date.strftime("%y-%m-%d-%I") %>
						<% else %>
							<%= f.text_field :release_date  %>
						<% end %> 
					</div>
				</div>
			</td>
		</tr>

		<tr>
			<td>
				<div class="t_ht"><div class="txt"><%= f.label :submit_date, '提出日（札幌）:' %></div></div>
			</td>

			<td>
				<div class="d2_ht">
					<div class="txt">
						<% if pa_link.work.present? %>
							<%= f.text_field :submit_date, value: pa_link.work.submit_date.strftime("%y-%m-%d-%I") %>
						<% else %>
							<%= f.text_field :submit_date %>
						<% end %>
					</div>
				</div>
			</td>

			<td>
				<div class="t_ht"><div class="txt"><%= f.label :testup, 'テストアップ:' %></div></div>
			</td>

			<td>
				<div class="d2_ht">
					<div class="txt">
						<% if pa_link.work.present? %>
							<%= f.text_field :testup, value: time_format(pa_link.work.testup) %>
						<% else %>
							<%= f.text_field :testup  %>
						<% end %>
					</div>
				</div>
			</td>
		</tr>

		<tr>
			<td>
				<div class="t_ht"><div class="txt"><%= f.label :urls, '対象URL:' %></div></div>
			</td>

			<td colspan = 3>
				<div class="d_ht">
					<div class="frm">
						<% if pa_link.work.present? %>
							<%= f.text_area :urls, value: pa_link.work.urls  %>
						<% else %>
							<%= f.text_area :urls %>
						<% end %>

					</div>
				</div>
			</td>
		</tr>

		<tr>
			<td>
				<div class="t_ht"><div class="txt"><%= f.label :contact, '作業内容:' %></div></div>
			</td>

			<td colspan = 3>
				<div class="d_ht">
					<div class="frm">
						<% if pa_link.work.present? %>
							<%= f.text_area :contact, value: pa_link.work.contact  %>
						<% else %>
							<%= f.text_area :contact %>
						<% end %>

					</div>
				</div>
			</td>


		</tr>
		<tr>
			<td><div class="t_ht"><div class="txt"><label>添付：</label></div></div></td>
				<td>
				<div class="d2_ht">
					<div class="frm">
						<%= f.file_field :attached_file %>
						<% unless pa_link.work.file_name.blank? %> 
							<div class="file1">
								・ <a href="<%= pa_link.work.attached_file %>">
									<%= pa_link.work.file_name %>
								  </a>
							</div>
						<% end %>	
					</div>
				</div>
			</td>

			<td>	
				<div class="t_ht"><div class="txt"><%= f.label :estimation, '見込み工数:' %></div></div>
			</td>
			<td>
				<div class="d2_ht">
					<div class="txt">
						<% if pa_link.work.present? %>
							<%= f.text_field :estimation, value: pa_link.work.estimation %>
						<% else %>
							<%= f.text_field :estimation, placeholder: 'h（修正がある場合)' %>
						<% end %>
					</div>
				</div>
			</td>
		</tr>
	</table> 
<!-- Radio -->
<div class="innerStepRadio clearfix">
	<div id="sts">
	    <%= f.label '進捗：' %>
	    <label>
	      <%= radio_button_tag :process, '着手可' %>
	      <p class="nam">着手可</p>
	    </label>

	    <label>
	      <%= radio_button_tag :process, '画像等・準備中' %>
	      <p class="nam">画像等、準備中</p>
	    </label> 
	     <span id="p_error">Please check!</span>
	</div>
</div>

<%= render partial:"edit/update_btn", locals: {f: f, pa_link: pa_link} %>
<% end %>

app/views/edit/_form_dircheck.html.erb
<h2 class="popup">
	<%= image_tag 'popup/tit_h2_dir_check.gif', alt: 'Dirチェック中', width: 113, height: 18 %>
</h2>

<%= form_for( pa_link, html: { class: 'edit-form', multipart: true }) do |f| %>
	 <%= hidden_field_tag :project_id, @project.id %> 
	 <%= hidden_field_tag :track, @start_time %>
	  
	<table>
		<tr>
			<td>
				<div class="t_ht"><div class="txt"><%= f.label :check_name, '担当名:' %></div></div>
			</td>

			<td>
				<div class="d2_ht">
					<div class="txt">
						<% if pa_link.work.present? %>
							<%= f.text_field :check_name, value: pa_link.work.check_name %>
						<% else %>
							<%= f.text_field :check_name %>
						<% end %>
					</div>
				</div>
			</td>

			<td>
				<div class="t_ht"><div class="txt"><%= f.label :estimation, '見込み工数:' %></div></div>
			</td>

			<td>
				<div class="d2_ht">
					<div class="txt">
						<% if pa_link.work.present? %>
							<%= f.text_field :estimation, value: pa_link.work.estimation %>
						<% else %>
							<%= f.text_field :estimation, placeholder: 'h（修正がある場合)' %>
						<% end %>
					</div>
				</div>
			</td>
		</tr>

		<tr>
			<td>
				<div class="t_ht"><div class="txt"><%= f.label :contact, '修正事項:' %></div></div>
			</td>

			<td colspan = 3>
				<div class="d_ht">
					<div class="frm">   
						<%= f.text_area :contact, :value => pa_link.work.contact  %> 
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td><div class="t_ht"><div class="txt"><label>添付：</label></div></div></td>
				<td colspan = 3>
				<div class="d_ht">
					<div class="frm">
						<%= f.file_field :attached_file %>
						<% unless pa_link.work.file_name.blank? %> 
							<div class="file1">
								・ <a href="<%= pa_link.work.attached_file %>">
									<%= pa_link.work.file_name %>
								  </a>
							</div>
						<% end %>	
					</div>
				</div>
			</td>
		</tr>
	</table>
<!-- Radio -->
<div class="innerStepRadio clearfix">
	<div id="sts">
	    <%= f.label '進捗：' %>
	    <label>
	      <%= radio_button_tag :process, '初稿確認出し中' %>
	      <p class="nam">テストアップ</p>
	    </label>

	    <label>
	      <%= radio_button_tag :process, '初稿内校戻し' %>
	      <p class="nam">修正アリ</p>
	    </label>
	     <span id="p_error">Please check!</span>
	</div>
</div>

<%= render partial:"edit/update_btn", locals: {f: f, pa_link: pa_link} %>
<% end %>

app/views/edit/_form_edit_work.html.erb
<h2 class="popup">
	<%= reverse_h2_title(work_count) %>
</h2>

<%= form_for(pa_link,  html: { class: 'edit-form', multipart: true }) do |f| %>
	 <%= hidden_field_tag :project_id, @project.id %> 
	 <%= hidden_field_tag :track, @start_time %>
	  
	<table>
		<tr>
			<td>
				<div class="t_ht"><div class="txt"><%= f.label :charge_name, '担当名:' %></div></div>
			</td>

			<td>
				<div class="d_ht">
					<div class="frm">
						<%= pa_link.work.charge_name %>
					</div>
				</div>
			</td>
		</tr>

		<tr>
				<td>
					<div class="t_ht"><div class="txt"><%= f.label :contact, '確認事項:' %></div></div>
				</td>

				<td>
					<div class="d_ht">
						<div class="frm">
								<%= f.text_area :contact, value: pa_link.work.contact  %>
						</div>
					</div>
				</td>
		</tr>

		<tr>
				<td>
					<div class="t_ht"><div class="txt"><%= f.label :jobs, '初回job:' %></div></div>
				</td>

				<td>
					<div class="d_ht">
						<div class="frm">
							<%= f.text_area :jobs, value: pa_link.work.jobs  %>
						</div>
					</div>
				</td>
		</tr>

		<tr>
			<td><div class="t_ht"><div class="txt"><label>添付：</label></div></div></td>
			<td>
				<div class="d_ht">
					<div class="frm">
						<%= f.file_field :attached_file %>
						<% unless pa_link.work.file_name.blank? %> 
							<div class="file1">
								・ <a href="<%= pa_link.work.attached_file %>">
									<%= pa_link.work.file_name %>
								  </a>
							</div>
						<% end %>	
					</div>
				</div>
			</td>
		</tr>
	</table>
<!-- Radio -->
<div class="innerStepRadio clearfix">
	<div id="sts">
	    <%= f.label '進捗：' %>
	    <label>
	      <%= radio_button_tag :process, 'Wチェック待ち' %>
	      <p class="nam">Wチェック待ち</p>
	    </label>

	    <label>
	      <%= radio_button_tag :process, '作業ストップ' %>
	      <p class="nam">作業ストップ</p>
	    </label>
	     <span id="p_error">Please check!</span>
	</div>
</div>

<%= render partial:"edit/update_btn", locals: {f: f, pa_link: pa_link} %>
<% end %>

app/views/edit/_form_image_upload.html.erb
<h2 class="popup">
	<%= image_tag 'popup/tit_h2_img_files_preparation.gif', alt: '画像等、準備中', width: 113, height: 18 %>
</h2>

<%= form_for( pa_link, html: { class: 'edit-form', multipart: true }) do |f| %>
	 <%= hidden_field_tag :project_id, @project.id %> 
	 <%= hidden_field_tag :track, @start_time %>
		<table>
			<tr>
				<td><div class="t_ht"><div class="txt"><label>添付：</label></div></div></td>
				<td>
					<div class="d_ht">
						<div class="frm">
							<%= f.file_field :attached_file %>
							<% unless pa_link.work.file_name.blank? %> 
								<div class="file1">
									・ <a href="<%= pa_link.work.attached_file %>">
										<%= pa_link.work.file_name %>
									  </a>
								</div>
							<% end %>	
						</div>
					</div>
				</td>
			</tr>
		</table>
<!-- Radio -->
<div class="innerStepRadio clearfix">
	<div id="sts">
	    <label> 進捗：</label>
	    <label>
	      <%= radio_button_tag :process, '着手' %>
	      <p class="nam">着手可</p>
	    </label>
	     <span id="p_error">Please check!</span> 
	</div>
</div> 

<%= render partial:"edit/update_btn", locals: {f: f, pa_link: pa_link} %>
<% end %>

app/views/edit/_form_project.html.erb
<%= form_for(@project, html: { id: 'project-form', multipart: true }) do |f| %>
  <% if @project.persisted? %>
    <%= hidden_field_tag :id, @project.id %>        
  <% end %>
  <%= hidden_field_tag :track, @start_time %>
  <%= f.hidden_field :working, value: "0" %>
  <%= f.hidden_field :draft, value: "0" %>
   
  <% if @project.attached_file_cache.present? %>     
    <%= hidden_field_tag  :file_upload,  @project.attached_file %>  
  <% end %>
<!-- Begin Form -->
<hr>
<div id="innerStep1" class="clearfix">
  <div><!-- Begin case -->
    <%= f.label :category, '案件区分:' %>
    <% f.select :category, Project.categories_for_options, include_blank: '&ndash; 選択してください &ndash;' %>
    <select id="project_category" name="project[category]">
      <option value="default">&ndash; 選択してください &ndash;</option>
      <option value="amc" <%= @project.category=='amc'?'selected':''%> >AMC運用</option>
      <option value="int" <%= @project.category=='int'?'selected':''%> >INT運用</option>
      <option value="wws" <%= @project.category=='wws'?'selected':''%> >WWS運用</option>
      <option value="etc" <%= @project.category=='etc'?'selected':''%> >ETC</option>
    </select>
  </div><!-- End case -->
  <div><!-- Begin case number -->
    <%= f.label :number, '案件番号:' %>
    <%= f.text_field :number, value: (@project.number ? @project.number : '' ) %> 
  </div><!-- End case number -->

  <div class="lastFrom"><!-- Begin release -->
    <%= f.label :release_date, 'リリース日:' %>
    <%= f.text_field :release_date, placeholder: 'yy-mm-dd-hh', value: (@project.release_date ? @project.release_date.strftime('%y-%m-%d-%H') : '' ) %>
  </div><!-- End release -->
</div>

<div id="innerStep2" class="clearfix">
  <div>
    <%= f.label :name, '案件名:' %>
    <%= f.text_area :name %>

  </div>
</div>

<div id="innerStep3" class="clearfix">
  <div class="texttype2">
    <%= f.label :submit_date do %>
      提出日<br>（札幌）:
    <% end %>
    <%= f.text_field :submit_date, placeholder: 'yy-mm-dd-hh', value: (@project.submit_date ? @project.submit_date.strftime('%y-%m-%d-%H') : '' ) %>
  </div>
  <div>
    <%= f.label :testup, 'テストアップ:' %>
    <%= f.text_field :testup, placeholder: 'yy-mm-dd-hh', value: (@project.testup ? @project.testup.strftime('%y-%m-%d-%H') : '' )  %>
  </div>
  <div class="lastFrom">
    <%= f.label :estimation, '見込み工数:' %>
    <%= f.text_field :estimation, placeholder: 'h' %>
  </div>
</div>

<div id="innerStep4" class="clearfix">
  <div>
    <%= f.label :urls, '対象URL：' %>
    <%= f.text_area :urls %>
  </div>
</div>

<div id="innerStep5" class="clearfix">
  <div>
    <%= f.label :content, '作業内容：' %>
    <%= f.text_area :content %>
  </div>
</div>

<div id="innerStep6" class="clearfix">
  <div class="balnk_file">
    <%= f.label :attached_file, '添付：' %>
    <%= f.file_field :attached_file %>    
  </div>
  
  <div class ="attached_file"> 
    <% unless @project.file_name.blank? %> 
      <div class="file1"> 
        ・ <a href="<%= @project.attached_file %>">
            <%= @project.file_name %>
          </a>
      </div>
    <% end %> 
  </div>
</div>

<div class="innerStepRadio  clearfix">
<!-- Radio -->
  <div id="sts">
    <%= f.label :progress, '進捗：' %>
    <label>
      <%= radio_button_tag :progress, '着手可' ,(params[:progress] == '着手可')%>
      <p class="nam">着手可</p>
    </label>
    <label>
      <%= radio_button_tag :progress, '画像等・準備中', (params[:progress] == '画像等・準備中') %>
      <p class="nam">画像等・準備中</p>
    </label>
  </div>
</div>

<%= render partial:"edit/update_btn", locals: {f: f, pa_link: @project.pa_links.first} %>

<% end %>
<!-- End Form -->

app/views/edit/_form_release_check.html.erb
<h2 class="popup">	
	<%= image_tag 'popup/tit_h1_release_check.gif', alt: 'リリース待機', width: 151, height: 18 %>
</h2>

<%= form_for( pa_link, html: { class: 'edit-form', multipart: true }) do |f| %>
	<%= hidden_field_tag :project_id, @project.id %> 
	<%= hidden_field_tag :track, @start_time %>	 	 
	  	 
	<table>
		<tr>
			<td>
				<div class="t_ht"><div class="txt"><%= f.label :charge_name, '担当名:' %></div></div>
			</td>

			<td>
				<div class="d_ht">
					<div class="frm">							 
						<%= pa_link.work.charge_name %>
					</div>
				</div>
			</td>
		</tr>

		<tr>
				<td>
					<div class="t_ht"><div class="txt"><%= f.label :contact, '連絡事項:' %></div></div>
				</td>

				<td>
					<div class="d_ht">
						<div class="frm">	
							<% if pa_link.work.present? %>
								<%= f.text_area :contact, value: pa_link.work.contact %>
							<% else %>
								<%= f.text_area :contact  %>	
							<% end %> 								  
						</div>
					</div>
				</td>
		</tr> 
		<tr>
			<td><div class="t_ht"><div class="txt"><label>添付：</label></div></div></td>
			<td>
				<div class="d_ht">
					<div class="frm">
						<%= f.file_field :attached_file %>
						<% unless pa_link.work.file_name.blank? %> 
							<div class="file1">
								・ <a href="<%= pa_link.work.attached_file %>">
									<%= pa_link.work.file_name %>
								  </a>
							</div>
						<% end %>	
					</div>
				</div>
			</td>
		</tr>
	</table>
<!-- Radio -->
<div class="innerStepRadio clearfix">
	<div id="sts">
	    <%= f.label '進捗：' %>
	    <label>
	      <%= radio_button_tag :process, 'リリース後チェック完了' %>
	      <p class="nam">リリース後チェック完了</p>
	    </label>
	 
	    <span id="p_error">Please check!</span> 
	</div>
</div>
<%= render partial:"edit/update_btn", locals: {f: f, pa_link: pa_link} %>
<% end %>

app/views/edit/_form_release_request.html.erb
<h2 class="popup">
	<%= image_tag 'popup/tit_h2_release_request.gif', alt: 'Dir作業中', width: 275, height: 18 %>
</h2>
 
<%= form_for( pa_link, html: { class: 'edit-form', multipart: true }) do |f| %>
	 <%= hidden_field_tag :project_id, @project.id %> 
	 <%= hidden_field_tag :track, @start_time %>
	  
	 <table>
		<tr>
			<td>
				<div class="t_ht"><div class="txt"><label>担当名:</label></div></div>
			</td>

			<td>
				<div class="d2_ht">
					<div class="txt">
						<% if pa_link.work.present? %>
							<%= pa_link.work.charge_name %>
						<% else %>
							<%= f.text_field :charge_name %>
						<% end %>
					</div>
				</div>
			</td>

			<td>
				<div class="t_ht"><div class="txt"><label>リリース日：</label></div></div>
			</td>

			<td>
				<div class="d2_ht">
					<div class="txt">
						<% if pa_link.work.present? %>
							<%= f.text_field :release_date, value: pa_link.work.release_date.strftime("%y-%m-%d-%I") %>
						<% else %>
							<%= f.text_field :release_date  %>
						<% end %>
					</div>
				</div>
			</td>
		</tr>	 

		<tr>
			<td>
				<div class="t_ht"><div class="txt"><label>対象URL</label></div></div>
			</td>

			<td colspan = 3>
				<div class="d_ht">
					<div class="frm">
						<% if pa_link.work.present? %>
							<%= f.text_area :urls, value: pa_link.work.urls  %>
						<% else %>
							<%= f.text_area :urls %>
						<% end %>
					</div>
				</div>
			</td>
		</tr>

		<tr>
			<td>
				<div class="t_ht"><div class="txt"><label>控えていたjob:</label></div></div>
			</td>

			<td colspan = 3>
				<div class="d_ht">
					<div class="frm">
						<% if pa_link.work.present? %>
							<%= f.text_area :jobs, value: pa_link.work.jobs  %>
						<% else %>
							<%= f.text_area :jobs %>
						<% end %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td><div class="t_ht"><div class="txt"><label>添付：</label></div></div></td>
				<td colspan = 3>
				<div class="d_ht">
					<div class="frm">
						<%= f.file_field :attached_file %>
						<% unless pa_link.work.file_name.blank? %> 
							<div class="file1">
								・ <a href="<%= pa_link.work.attached_file %>">
									<%= pa_link.work.file_name %>
								  </a>
							</div>
						<% end %>
					</div>
				</div>
			</td>
		</tr>
	</table>
<!-- Radio -->
<div class="innerStepRadio clearfix">
	<div id="sts">
		 <%= f.label '進捗：' %>
	    <label>
	      <%= radio_button_tag :process, 'Fix、リリース前チェック' %>
	      <p class="nam">リリース前チェック着手</p>
	    </label>
	     <span id="p_error">Please check!</span>
	</div>
</div>

<%= render partial:"edit/update_btn", locals: {f: f, pa_link: pa_link} %>
<% end %>

app/views/edit/_form_uchiko.html.erb
<h2 class="popup">
	<%= image_tag 'popup/tit_h2_uchiko_img_file.gif', alt: '内校戻し作業中', width: 189, height: 18 %>
</h2>

<%= form_for( pa_link, html: { class: 'edit-form', multipart: true }) do |f| %>
	 <%= hidden_field_tag :project_id, @project.id %> 
	 <%= hidden_field_tag :track, @start_time %>
		<table>
			<tr>
				<td><div class="t_ht"><div class="txt"><label>添付：</label></div></div></td>
				<td>
					<div class="d_ht">
						<div class="frm">							
							<%= f.file_field :attached_file %>

							<% unless pa_link.work.file_name.blank? %> 
								<div class="file1">
									・ <a href="<%= pa_link.work.attached_file %>">
										<%= pa_link.work.file_name %>
									  </a>
								</div>
							<% end %>	
						</div>
					</div>
				</td>
			</tr>
		</table>
<!-- Radio -->
<div class="innerStepRadio clearfix">
	<div id="sts">
	    <%= f.label '進捗：' %>
	    <label>
	      <%= radio_button_tag :process, '内校戻し' %>
	      <p class="nam">着手</p>
	    </label>
	    <!-- 
	    <label>
	      <%= radio_button_tag :process, '内校戻し中断' %>
	      <p class="nam">修正アリ</p>
	    </label>
	-->
	     <span id="p_error">Please check!</span>
	</div>
</div>

<%= render partial:"edit/update_btn", locals: {f: f, pa_link: pa_link} %>
<% end %>

app/views/edit/_update_btn.html.erb
<div class="innerStepBtn clearfix">
<!-- Buttons -->
  <div>    
    <dl>
      <dt><%= f.submit '更 新' , id: :submit_btn, :confirm => "本当に更新しますか?" %></dt> 

      <% if pa_link.id < @project.pa_links.last.id  %>
        <dd class="progress">        
          <%= link_to pa_link_path(pa_link.id ), :confirm => "本当に進捗をここまで戻しますか？", :method => :delete do %>
            <button type="submit" id="backBtn">進捗をここまで戻す</button>
          <% end %>
        </dd>
      <% end %>
    </dl>
  </div>
</div>